apiVersion: v1
data:
  secretToken: bXktc3VwZXItc2VjdXJlLWludGVyY2VwdG9yLXBhc3N3b3Jk
kind: Secret
metadata:
  name: github-interceptor-secret
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-trigger
spec:
  serviceAccountName: tekton-trigger
  triggers:
    - name: push-build
      interceptors:
        - github:
            secretRef:
              secretName: github-interceptor-secret
              secretKey: secretToken
            eventTypes: ["push"]
      bindings:
       - ref: tekton-trigger
      template:
        name: tekton-trigger